Update plugin to support new HostedExperience interface
spiffdev/woocommerce-plugin pull request #13
Opened 2023-06-06 02:23 UTC by ngchphuong

2023-06-08 04:05 UTC, elInfidel requested changes

2023-06-08 04:05 UTC, elPixelador commented on spiff-connect/spiff-connect.php
> +define("SPIFF_API_BASE", "https://api.spiff.com.au");
Why has this been changed to be hardcoded?

2023-06-08 04:05 UTC, elPixelador commented on spiff-connect/spiff-connect.php
> +        plugin_dir_url(__FILE__) . 'public/js/create-design-button.js'.'?'.rand(),
What is the purpose of adding rand here?

2023-06-08 04:05 UTC, elPixelador commented on spiff-connect/public/js/create-design-button.js
> +//window.spiffAppendCreateDesignButtonBulk = spiffAppendCreateDesignButtonBulk;
Why has bulk mode been commented out?

2023-06-08 04:05 UTC, elPixelador commented on spiff-connect/spiff-connect.php
> +define("SPIFF_API_BASE", "https://api.spiff.com.au");
During the build process for woocommerce we place the file here.

spiff-connect/public/js/api.js

You can add it hear manually to see it working using that path

2023-06-08 04:24 UTC, ngchphuong commented on spiff-connect/spiff-connect.php
> +        plugin_dir_url(__FILE__) . 'public/js/create-design-button.js'.'?'.rand(),
Sorry, let me remove it, just use it to force cache

2023-06-08 04:27 UTC, ngchphuong commented on spiff-connect/public/js/create-design-button.js
> +//window.spiffAppendCreateDesignButtonBulk = spiffAppendCreateDesignButtonBulk;
Just for debug something, we will revert it. Thank you!

2023-06-09 05:39 UTC, elInfidel approved these changes

2023-06-09 05:39 UTC, elInfidel commented on spiff-connect/public/js/create-design-button.js
> +  //integrationProduct.on('invalid', () => console.error("Spiff product could not be found."));
Why has this been commented?

2023-06-29 03:33 UTC, elInfidel approved these changes

2023-06-29 03:33 UTC, merged